apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: ScalewayMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-scaleway
    app.kubernetes.io/managed-by: kustomize
  name: scalewaymachinetemplate-sample
spec:
  # TODO(user): Add fields here
