labels:
- pairs:
    cluster.x-k8s.io/v1beta1: v1alpha1
    cluster.x-k8s.io/v1beta2: v1alpha2

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_scalewayclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewaymachines.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewayclustertemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewaymachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewaymanagedclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewaymanagedcontrolplanes.yaml
- bases/infrastructure.cluster.x-k8s.io_scalewaymanagedmachinepools.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_scalewayclusters.yaml
- path: patches/webhook_in_scalewaymachines.yaml
- path: patches/webhook_in_scalewayclustertemplates.yaml
- path: patches/webhook_in_scalewaymachinetemplates.yaml
- path: patches/webhook_in_scalewaymanagedclusters.yaml
- path: patches/webhook_in_scalewaymanagedcontrolplanes.yaml
- path: patches/webhook_in_scalewaymanagedmachinepools.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
